project_id = "qiiuvlmauztjitflqcfd"

[functions.search-books]
verify_jwt = false

[functions.rapid-action]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.clube-ai]
verify_jwt = true

[functions.leitura-copiloto]
verify_jwt = true

[functions.salvar-progresso-leitura]
verify_jwt = true

[functions.ensure-profiles]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.obra-estatisticas]
verify_jwt = false

[functions.reprocessar-autores]
verify_jwt = false

[functions.conciliar-autor]
verify_jwt = false

[functions.reprocessar-generos]
verify_jwt = false

[functions.reprocessar-obras]
verify_jwt = false

[functions.conciliar-obra]
verify_jwt = false

